apiVersion: apps/v1
kind: Deployment
metadata:
  name: ceri-deployment
  labels:
    app: certi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: certi
  template:
    metadata:
      labels:
        app: certi
    spec:
      containers:
      - name: certi
        image: gcr.io/model-framing-308812/certi
        ports:
        - containerPort: 80
