# This file configures the hello-world app which serves public web traffic.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: certi-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: certi
  template:
    metadata:
      labels:
        app: certi
    spec:
      containers:
      - name: certi
        # Replace $GCLOUD_PROJECT with your project ID
        image: gcr.io/model-framing-308812/certi:v1
        # This app listens on port 8080 for web traffic by default.
        ports:
        - containerPort: 8000
        env:
          - name: PORT
            value: "8000"
