apiVersion: apps/v1
kind: Deployment
metadata:
  name:  certificate-deploy
  labels:
    name:  certificate
spec:
  replicas: 3
  selector:
    matchLabels:
      os: ubuntu
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        os: ubuntu
    spec:
      containers:
      - image:  gcr.io/model-framing-308812/certi:v1
        imagePullPolicy: Always
        name:  my-name
        command: [ "/bin/bash", "-ec"]
        args: [ date; sleep 10; echo 'Hello from the Kubernetes cluster'; sleep 1; while true; do sleep 20; done;]
        resources:
          limits:
            cpu: "100m"
            memory: "500Mi"      
        ports:
        - containerPort:  80
          name:  my-name
      restartPolicy: Always
