apiVersion: apps/v1
kind: Deployment
metadata:
  name: certi-deployment
spec:
 selector:
  matchlabels:
    app: certi
     replicas: 1
  template:
    metadata:
      labels:
        app: certi
    spec:
      containers:
      - name: certi
        image: python 3.7
        ports:
        - containerPort: 80
