apiVersion: apps/v1
kind: Deployment
metadata:
  name: certi-deployment
spec:
 selector:
  matchlabels:
    app: certi
     replicas: 3
  template:
    metadata:
      labels:
        app: certi
    spec:
      containers:
      - name: certi
        image: gcr.io/model-framing-308812/certi
        ports:
        - containerPort: 80
